# Generated by Django 2.1.4 on 2019-04-10 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_dash', '0003_auto_20190410_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_url',
            field=models.FilePathField(default='photo.jpg'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
