# Generated by Django 2.1.4 on 2019-04-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_dash', '0004_auto_20190410_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_url',
            field=models.FilePathField(),
        ),
    ]
