# Generated by Django 2.1.4 on 2019-04-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_dash', '0005_auto_20190410_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='result',
            field=models.FilePathField(verbose_name='结果序列化文件'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_url',
            field=models.CharField(max_length=255),
        ),
    ]
