# Generated by Django 2.1.4 on 2019-04-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_dash', '0007_auto_20190414_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='config',
            field=models.TextField(default={}, null=True),
        ),
    ]
